
test: *.cpp *.h
	g++ -Wall -g test_main.cpp test_suffixtree_alloccurs.cpp test_suffixtree_processpositions.cpp test_suffixtree_simple.cpp test_suffixtree_random.cpp test_suffixtree_time.cpp test_suffixnode.cpp ../SuffixNode.cpp ../tialloc/tialloc.cpp -o test -I.. -I../tialloc
clean:
	rm test
