
test: *.cpp *.h ../*.cpp ../*.h
	g++ -Wall -O3 test_main.cpp test_suffixtree_alloccurs.cpp test_suffixtree_processpositions.cpp test_suffixtree_simple.cpp test_suffixtree_random.cpp test_suffixtree_time.cpp test_suffixnode.cpp ../SuffixNode.cpp ../tialloc/tialloc.cpp ../SuffixNodeStoreMemVec.cpp -o test -I.. -I../tialloc -I.
clean:
	rm test
